stepshop/authapp/urls.py
from django.urls import path

from authapp.views import login, logout

app_name = 'auth'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

stepshop/stepshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from stepshop.views import index, contacts, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from stepshop.views import index, contacts, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class ShopUser(AbstractUser):
    avatar = models.ImageField(
        upload_to='users_avatars',
        blank=True,
        verbose_name="Аватарка",
    )

    age = models.PositiveIntegerField(
        verbose_name='возраст',
    )

stepshop/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm

from authapp.models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = {'username', 'password'}

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

stepshop/authapp/views.py
from django.contrib import auth
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from authapp.forms import ShopUserLoginForm


def login(request):
    title = 'вход'

    login_form = ShopUserLoginForm(data=request.POST)

    context = {
        'title': title,
        'login_form': login_form,
    }

    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

stepshop/stepshop/views.py
from django.shortcuts import render

links_menu = [
    {'href': 'index', 'name': 'Домой', 'route': ''},
    {'href': 'products:index', 'name': 'Продукты', 'route': 'products/'},
    {'href': 'about', 'name': 'О&nbsp;нас', 'route': 'about/'},
    {'href': 'contacts', 'name': 'Контакты', 'route': 'contacts/'},
]


def index(request):
    title = 'главная страница'

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'index.html', context)
    # return render(request=request, template_name='index.html', context=context)


def about(request):
    title = 'о нас'

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'about.html', context)


def contacts(request):
    title = 'контакты'

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'contact.html', context)

stepshop/stepshop/templates/authapp/_register.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
    {{ title|capfirst }}
{% endblock %}

{% block content %}

<div class="container">

    <h1>{{ title|capfirst }}</h1>

    <div class="row">
        <div class="mx-auto col-3">
            <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ register_form.as_p }}
                <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            </form>
        </div>
    </div>
</div>


{% endblock %}

stepshop/stepshop/templates/authapp/edit.html
{% extends '../base.html' %}
{% load static %}
{% load my_tags %}

{% block title %}
    {{ title|capfirst }}
{% endblock %}

{% block content %}

<div class="container">

    <h1>{{ title|capfirst }}</h1>

    <div class="row">
        <div class="mx-auto col-4">

            <div class="user_avatar">
                <img height="150px" width="150px" src="{{ user.avatar|media_folder_user }}" alt="{{ user.username }}" class="rounded-circle">
            </div>

            <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ edit_form.as_p }}

                <button type="submit" class="btn btn-primary">Сохранить</button>
            </form>

            <button class="btn btn-primary">
                <a href="{% url 'index' %}" class="text-light">На главную</a>
            </button>
        </div>
    </div>
</div>


{% endblock %}

stepshop/stepshop/templates/authapp/login.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
    {{ title|capfirst }}
{% endblock %}

{% block content %}

<div class="container">

    <h1>{{ title|capfirst }}</h1>

    <div class="row">
        <div class="mx-auto col-3">
            <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
                {% csrf_token %}
                {{ login_form.as_p }}
                <button type="submit" class="btn btn-primary">Войти</button>
            </form>
        </div>
    </div>

</div>


{% endblock %}

stepshop/stepshop/templates/authapp/register.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
    {{ title|capfirst }}
{% endblock %}

{% block content %}

<div class="container">

    <h1>{{ title|capfirst }}</h1>

    <div class="row">
        <div class="mx-auto col-4">
            <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>
                    <label for="login">Логин:</label>
                    {{ register_form.username }}
                </p>
                <p>
                    <label for="first_name">Имя:</label>
                    {{ register_form.first_name }}

                </p>
                <p>
                    <label for="password1">Пароль:</label>
                    {{ register_form.password1 }}
                    {{ register_form.errors.password1 }}
                </p>
                <p>
                    <label for="password2">Подтверждение пароля:</label>
                    {{ register_form.password2 }}
                    {{ register_form.errors.password2 }}
                </p>
                <p>
                    <label for="email">E-mail:</label>
                    {{ register_form.email }}
                    {{ register_form.errors.email }}

                </p>
                <p>
                    <label for="age">Возраст:</label>
                    {{ register_form.age }}
                    {{ register_form.errors.age }}

                </p>
                <p>
                    <label>Аватарка:
                        {{ register_form.avatar }}
                    </label>
                </p>

                <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            </form>
        </div>
    </div>
</div>


{% endblock %}