stepshop/basketapp/urls.py
from django.urls import path

from basketapp.views import basket, basket_add, basket_remove

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>/', basket_remove, name='remove'),
]

stepshop/stepshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from stepshop.views import index, contacts, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from stepshop.views import index, contacts, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/basketapp/models.py
from django.db import models

from mainapp.models import Product
from stepshop import settings


class Basket(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='basket',
    )

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
    )

    quantity = models.PositiveIntegerField(
        verbose_name='количество',
        default=0,
    )

    add_datetime = models.DateTimeField(
        verbose_name='время',
        auto_now_add=True,
    )

    @property
    def product_cost(self):
        return self.product.price * self.quantity

    @property
    def total_quantity(self):
        _items = Basket.objects.filter(user=self.user)
        _total_quantity = sum(list(map(lambda x: x.quantity, _items)))
        return _total_quantity

    @property
    def total_cost(self):
        _items = Basket.objects.filter(user=self.user)
        _total_cost = sum(list(map(lambda x: x.product_cost, _items)))
        return _total_cost

stepshop/basketapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from basketapp.models import Basket
from mainapp.models import Product

links_menu = [
    {'href': 'index', 'name': 'Домой', 'route': ''},
    {'href': 'products:index', 'name': 'Продукты', 'route': 'products/'},
    {'href': 'about', 'name': 'О&nbsp;нас', 'route': 'about/'},
    {'href': 'contacts', 'name': 'Контакты', 'route': 'contacts/'},
]



@login_required
def basket(request):
    if request.user.is_authenticated:
        basket_ = Basket.objects.filter(user=request.user)

        context = {
            'basket': basket_,
            'links_menu': links_menu,
        }

        return render(request, 'basketapp/basket.html', context)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_add(request, pk):
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('products:product', args=[pk]))

    product = get_object_or_404(Product, pk=pk)

    basket_ = Basket.objects.filter(user=request.user, product=product).first()

    if not basket_:
        basket_ = Basket(user=request.user, product=product)

    basket_.quantity += 1
    basket_.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)
    basket_record.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

stepshop/stepshop/views.py
from django.shortcuts import render

links_menu = [
    {'href': 'index', 'name': 'Домой', 'route': ''},
    {'href': 'products:index', 'name': 'Продукты', 'route': 'products/'},
    {'href': 'about', 'name': 'О&nbsp;нас', 'route': 'about/'},
    {'href': 'contacts', 'name': 'Контакты', 'route': 'contacts/'},
]


def index(request):
    title = 'главная страница'

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'index.html', context)
    # return render(request=request, template_name='index.html', context=context)


def about(request):
    title = 'о нас'

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'about.html', context)


def contacts(request):
    title = 'контакты'

    context = {
        'title': title,
        'links_menu': links_menu,
    }

    return render(request, 'contact.html', context)

stepshop/stepshop/templates/basketapp/basket.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ title|capfirst }}
{% endblock %}


{% block content %}
    {% if user.is_authenticated %}
        <div class="container w-50 mt-5">
            <div class="row basket_list">
                <table class="table mt-3">
                    <thead>
                    <tr>
                        <th class="col-1">№</th>
                        <th class="col">Продукт</th>
                        <th class="col">Количество</th>
                        <th class="col">Стоимость</th>
                        <th class="col">Удалить</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in basket %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ item.product }}</td>
                            <td>{{ item.quantity }}</td>
                            <td>{{ item.product.price }}</td>
                            <td>
                                   <a href="{% url 'basket:remove' item.pk %}">
                                <button class="btn btn-danger">
                                 удалить
                                </button>
                                   </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>

                </table>
            </div>

            <div class="basket_summary">
                Всего товаров: <strong>{{ basket.0.total_quantity }}</strong><br>
                Общая стоимость: <strong>${{ basket.0.total_cost|floatformat:"g" }}<strong>
            </div>

        </div>

    {% endif %}
{% endblock %}